### ISSUE TITLE
Segmentation fault when parsing non-json message

### ISSUE THREAD

**Issue by rmeertens** [kbranigan/cJSON#14]
Anybody ever tried to parse a non-json message? For example: {"test":12

^^ Note that there is no ending accolade... 
For me this gives a segmentation fault. Would it be better if this would return an empty json object?

**Comment by anton-sergeev** [comment]
I tried your case:
```c
    cJSON *root = cJSON_Parse("{\"test\":12");
    if(root) {
        //do thomething
        cJSON_Delete(root);
    } else {
        fprintf(stderr, "ERROR: Cant parse:\n%s\n", str);
    }
```
No failures. But I get NULL pointer, so this should be correctly handled.

**Comment by davisjp1822** [comment]
I don't think this was the way that your test case works for how the code is written. Check out the cJSON_Parse code:

```c
cJSON *cJSON_ParseWithOpts(const char *value,const char **return_parse_end,int require_null_terminated)
{
	const char *end=0;
	cJSON *c=cJSON_New_Item();
	ep=0;
	if (!c) return 0;       /* memory fail */

	end=parse_value(c,skip(value));
	if (!end)	{cJSON_Delete(c);return 0;}	/* parse failure. ep is set. */

	/* if we require null-terminated JSON without appended garbage, skip and then check for a null terminator */
	if (require_null_terminated) {end=skip(end);if (*end) {cJSON_Delete(c);ep=end;return 0;}}
	if (return_parse_end) *return_parse_end=end;
	return c;
}
```
The function is returning 0 and setting the error printer `ep` when failing. If successful, the function is returning `c`, which is a new cJSON struct.

If I had to make a guess, your code is failing because your first statement:

```c
if(root)
```
Always evaluates to true, even if the JSON is invalid because root == 0. Then, when you try and do something with `root`, your program segfaults because memory hasn't been allocated.

**Comment by anton-sergeev** [comment]
The value 0 (zero) represents false, and all other values represent true.

**Comment by mitghi** [comment]
Agree, because pointer is NULL is not properly checked.
